import type { LogoParams, StyleFamily } from '../engine/types.ts'

export interface Preset {
  id: string
  modeId: string
  name: string
  description: string
  styleFamily: StyleFamily
  params: Partial<LogoParams>
}

export const PRESETS: Preset[] = [
  {
    id: 'radial-orbit',
    modeId: 'geometric-radial',
    name: 'Orbit Seal',
    description: 'Balanced circular symbol with neat orbital cuts.',
    styleFamily: 'minimal',
    params: {
      modeId: 'geometric-radial',
      generatorId: 'geometric-radial',
      styleFamily: 'minimal',
      seed: 142,
      gridRings: 4,
      symmetryFolds: 6,
      additiveRatio: 0.72,
      baseRadius: 0.38,
      radiusVariation: 0.32,
      animationSpeed: 0.8,
      fillColor: '#161616',
    },
  },
  {
    id: 'radial-crown',
    modeId: 'geometric-radial',
    name: 'Crown Burst',
    description: 'Sharp ceremonial symbol with engraved rhythm.',
    styleFamily: 'heritage',
    params: {
      modeId: 'geometric-radial',
      generatorId: 'geometric-radial',
      styleFamily: 'heritage',
      seed: 415,
      gridRings: 5,
      symmetryFolds: 8,
      additiveRatio: 0.6,
      baseRadius: 0.5,
      radiusVariation: 0.55,
      rotation: 12,
      fillColor: '#6f4627',
    },
  },
  {
    id: 'radial-signal',
    modeId: 'geometric-radial',
    name: 'Signal Bloom',
    description: 'Livelier abstract symbol with expressive offsets.',
    styleFamily: 'playful',
    params: {
      modeId: 'geometric-radial',
      generatorId: 'geometric-radial',
      styleFamily: 'playful',
      seed: 511,
      gridRings: 4,
      symmetryFolds: 7,
      additiveRatio: 0.68,
      baseRadius: 0.56,
      radiusVariation: 1.05,
      fillColor: '#0f5cc5',
      animationSpeed: 1.6,
    },
  },
  {
    id: 'modular-coin',
    modeId: 'modular',
    name: 'Coin Array',
    description: 'Compact grid clipped into a dense coin-like mark.',
    styleFamily: 'minimal',
    params: {
      modeId: 'modular',
      generatorId: 'modular',
      styleFamily: 'minimal',
      seed: 777,
      additiveRatio: 0.8,
      baseRadius: 0.34,
      radiusVariation: 0.1,
      fillColor: '#171717',
      modeParams: {
        modular: {
          columns: 5,
          rows: 5,
          circleClip: 1,
        },
      },
    },
  },
  {
    id: 'modular-lattice',
    modeId: 'modular',
    name: 'Lattice Crest',
    description: 'Hard-edged modular badge with old-world density.',
    styleFamily: 'heritage',
    params: {
      modeId: 'modular',
      generatorId: 'modular',
      styleFamily: 'heritage',
      seed: 688,
      additiveRatio: 0.58,
      baseRadius: 0.52,
      radiusVariation: 0.12,
      fillColor: '#74472c',
      modeParams: {
        modular: {
          columns: 4,
          rows: 6,
          circleClip: 1,
        },
      },
    },
  },
  {
    id: 'modular-matrix',
    modeId: 'modular',
    name: 'Matrix Tile',
    description: 'Tight technical tiling with restrained negative space.',
    styleFamily: 'tech',
    params: {
      modeId: 'modular',
      generatorId: 'modular',
      styleFamily: 'tech',
      seed: 294,
      additiveRatio: 0.84,
      baseRadius: 0.32,
      radiusVariation: 0.08,
      fillColor: '#0f172a',
      modeParams: {
        modular: {
          columns: 6,
          rows: 6,
          circleClip: 1,
        },
      },
    },
  },
  {
    id: 'grid-badge',
    modeId: 'grid-system',
    name: 'Badge Grid',
    description: 'Symmetric badge system with framed corridors.',
    styleFamily: 'heritage',
    params: {
      modeId: 'grid-system',
      generatorId: 'grid-system',
      styleFamily: 'heritage',
      seed: 322,
      additiveRatio: 0.66,
      fillColor: '#6f4627',
      modeParams: {
        'grid-system': {
          columns: 7,
          rows: 7,
          density: 0.6,
          cellInset: 0.08,
          strokeBias: 0.78,
          mirrorX: 1,
          mirrorY: 1,
          frameMode: 1,
        },
      },
    },
  },
  {
    id: 'grid-core',
    modeId: 'grid-system',
    name: 'Core Matrix',
    description: 'Crisp system mark with mirrored structural cuts.',
    styleFamily: 'tech',
    params: {
      modeId: 'grid-system',
      generatorId: 'grid-system',
      styleFamily: 'tech',
      seed: 901,
      additiveRatio: 0.82,
      fillColor: '#111827',
      modeParams: {
        'grid-system': {
          columns: 8,
          rows: 8,
          density: 0.5,
          cellInset: 0.12,
          strokeBias: 0.8,
          mirrorX: 1,
          mirrorY: 1,
          frameMode: 0,
        },
      },
    },
  },
  {
    id: 'grid-pop',
    modeId: 'grid-system',
    name: 'Pop Blocks',
    description: 'Loose graphic block mark with playful asymmetry.',
    styleFamily: 'playful',
    params: {
      modeId: 'grid-system',
      generatorId: 'grid-system',
      styleFamily: 'playful',
      seed: 115,
      additiveRatio: 0.7,
      fillColor: '#0d8e8f',
      modeParams: {
        'grid-system': {
          columns: 5,
          rows: 5,
          density: 0.68,
          cellInset: 0.08,
          strokeBias: 0.45,
          mirrorX: 0,
          mirrorY: 0,
          frameMode: 2,
        },
      },
    },
  },
  {
    id: 'monogram-atelier',
    modeId: 'monogram',
    name: 'Atelier',
    description: 'Elegant interlocked initials with framed presence.',
    styleFamily: 'luxe',
    params: {
      modeId: 'monogram',
      generatorId: 'monogram',
      styleFamily: 'luxe',
      seed: 440,
      fillColor: '#171311',
      brandInput: { initials: 'AM' },
      modeParams: {
        monogram: {
          strokeWeight: 1.1,
          contrast: 0.7,
          cornerStyle: 0,
          interlockStrength: 0.52,
          symmetryBias: 0.58,
          frameMode: 1,
        },
      },
    },
  },
  {
    id: 'monogram-crest',
    modeId: 'monogram',
    name: 'Crest',
    description: 'Heavier framed initials suited for heritage marks.',
    styleFamily: 'heritage',
    params: {
      modeId: 'monogram',
      generatorId: 'monogram',
      styleFamily: 'heritage',
      seed: 184,
      fillColor: '#623a22',
      brandInput: { initials: 'MC' },
      modeParams: {
        monogram: {
          strokeWeight: 1.38,
          contrast: 0.56,
          cornerStyle: 1,
          interlockStrength: 0.4,
          symmetryBias: 0.42,
          frameMode: 1,
        },
      },
    },
  },
  {
    id: 'monogram-spark',
    modeId: 'monogram',
    name: 'Spark',
    description: 'Brighter two-letter symbol with playful locking.',
    styleFamily: 'playful',
    params: {
      modeId: 'monogram',
      generatorId: 'monogram',
      styleFamily: 'playful',
      seed: 612,
      fillColor: '#0f5cc5',
      brandInput: { initials: 'PX' },
      modeParams: {
        monogram: {
          strokeWeight: 1.42,
          contrast: 0.34,
          cornerStyle: 2,
          interlockStrength: 0.66,
          symmetryBias: 0.22,
          frameMode: 2,
        },
      },
    },
  },
  {
    id: 'wave-signal',
    modeId: 'wave-arc',
    name: 'Signal',
    description: 'Bilateral crescents radiating like a broadcast signal.',
    styleFamily: 'minimal',
    params: {
      modeId: 'wave-arc',
      generatorId: 'wave-arc',
      styleFamily: 'minimal',
      seed: 256,
      fillColor: '#161616',
      rotation: 0,
      modeParams: {
        'wave-arc': {
          arcCount: 4, spreadAngle: 120, gapRatio: 0.3, taperAmount: 0.7,
          arcSymmetry: 'bilateral', symmetryFolds: 4,
        },
      },
    },
  },
  {
    id: 'wave-radial-pulse',
    modeId: 'wave-arc',
    name: 'Radial Pulse',
    description: 'Radial crescents fanning out from the center.',
    styleFamily: 'tech',
    params: {
      modeId: 'wave-arc',
      generatorId: 'wave-arc',
      styleFamily: 'tech',
      seed: 733,
      fillColor: '#0f172a',
      rotation: 0,
      modeParams: {
        'wave-arc': {
          arcCount: 3, spreadAngle: 160, gapRatio: 0.25, taperAmount: 0.95,
          arcSymmetry: 'radial', symmetryFolds: 6,
        },
      },
    },
  },
  {
    id: 'wave-ripple',
    modeId: 'wave-arc',
    name: 'Ripple',
    description: 'Dense bilateral waves with blunt, even strokes.',
    styleFamily: 'heritage',
    params: {
      modeId: 'wave-arc',
      generatorId: 'wave-arc',
      styleFamily: 'heritage',
      seed: 488,
      fillColor: '#6f4627',
      rotation: 0,
      modeParams: {
        'wave-arc': {
          arcCount: 7, spreadAngle: 90, gapRatio: 0.15, taperAmount: 0.3,
          arcSymmetry: 'bilateral', symmetryFolds: 4,
        },
      },
    },
  },
]
